<?php
/**
 * User: michael
 * Date: 28/08/2017
 * Time: 16:18
 */

if (!empty($_SERVER['SCRIPT_FILENAME']) && 'class.php' == basename($_SERVER['SCRIPT_FILENAME']))
    die ('Please do not load this page directly. Thanks!');

class following extends Plugins {

    public static $instance;
    public $name;

    function getClass() {
        $name =	get_class($this);
        $this->name = $name;
        return $name;
    }

    public static function getInstance() {
        if (!(self::$instance instanceof self)) {
            self::$instance = new self();
        }

        return self::$instance;
    }

    public function __construct() {
        parent::__construct($this->getClass());

        parent::setTitle('Following');
        parent::setDescription("Allows you see players that are being following by b3");
        parent::setVersion(1.0);
    }

    public function __destruct() {
        parent::__destruct();
    }

    /**
     * Get the title of the plugin
     */
    public function getTitle() {
        return parent::getTitle();
    }

    public function getDescription()
    {
        return parent::getDescription(); // TODO: Change the autogenerated stub
    }

}